apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/k8s/lnmp/db
    ##这里的IP，是NFS server的IP
    server: 192.168.168.219
